# Generated by Django 4.1.7 on 2023-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
